---

# Main tasks file for ssmtp role

- name: 'INIT | Manage variables to use for our target'
  include_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::ssmtp'
    - 'role::ssmtp::init'

- name: 'INSTALL | Manage ssmtp installation tasks'
  include_tasks:
    file: "{{ role_path }}/tasks/install_ssmtp.yml"
    apply:
      become: True
  tags:
    - 'role::ssmtp'
    - 'role::ssmtp::init'
    - 'role::ssmtp::install'

- name: 'CONFIG | Manage ssmtp config tasks'
  include_tasks:
    file: "{{ role_path }}/tasks/config.yml"
    apply:
      become: True
  tags:
    - 'role::ssmtp'
    - 'role::ssmtp::init'
    - 'role::ssmtp::install'
